### ISSUE TITLE
Add Ability to change downlaod path

### ISSUE THREAD

**Issue by Natrukei** [Lofter1/anyflip-downloader#10]
Windows doesn't allow \ as Folder Names and I had files with the title name with an ' and there the program tries to write \' .
So it would be good to change the temp save name next to the title name...

**Comment by Lofter1** [comment]
So you want an option to change the temporary download folder name? Did I get that right?

**Comment by Natrukei** [comment]
Yes exactly.

Or an "inntelligence" that the program auto-sanitizes folder paths it can't create on windows. That would work too and maybe even better.

**Comment by Lofter1** [comment]
This issue should be addressed in the newest commits. There are now ways to change the file path, but I also found a third party library that sanitises filenames. The filename should now be sanitised before anything is done with it.

**Comment by Natrukei** [comment]
It manages to download these now but the creation of the pdf failes.

**Comment by Natrukei** [comment]
EvenEven using -Title 1 does not work. It stills seems to be looking for the original name and thus fails to create the pdf.
