### ISSUE TITLE
I am a newbie and am unsure how to use it?

### ISSUE THREAD

**Issue by WombowSen** [Lofter1/anyflip-downloader#15]
I am deathly new to Github and to everything in general, I'm not sure what I should do in regards to doing it correctly. Could you treat me as someone who has never encountered github or any coding and tell me what i'm missing / doing wrong?

**Comment by Lofter1** [comment]
I need more details on order to help you. What is it, you have problems with?

**Comment by WombowSen** [comment]
Practically everything? I don't want to seem demanding but I have no programming 'experience' and so even if it is the bare minimum instructions I have no clue where to start. I don't know if I should install something or put something into a console- I don't have any clues

**Comment by Lofter1** [comment]
you simply download the program from the release page (https://github.com/Lofter1/anyflip-downloader/releases/tag/latest), unpack it, open CMD or PowerShell, go to the folder you have it saved in (copy the path from the file explorer and type `cd <path/to/exe>`, and then you execute the program by typing `./anyflip-downloader <anyflip URL>`. If you struggle with CMD or PowerShell, there should be some simple tutorials online. If you are not on Windows, do the same, just not using PowerShell or CMD, but using the Terminal.

**Comment by Lofter1** [comment]
I have now included an install script. Please follow the instruction in the README for your OS.
