### ISSUE TITLE
Hi, I've been following the advice online and think I've done everything right, but it still refuses to work.

### ISSUE THREAD

**Issue by Snekromancer** [Lofter1/anyflip-downloader#16]
I installed the package using `git clone` , navigated to the folder I created, then tried to use it and all I get is:

```
PS C:\Users\jay\documents\anyflip-downloader> ./anyflip-downloader https://anyflip.com/hveyv/chwx/
./anyflip-downloader : The term './anyflip-downloader' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ ./anyflip-downloader https://anyflip.com/hveyv/chwx/
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./anyflip-downloader:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

This happens also when I just try `anyflip-downloader https://anyflip.com/hveyv/chwx/`

I don't know if I just need to download something or I'm writing it wrong, but I'd love some clarification. I'm on Windows using Powershell.

**Comment by Lofter1** [comment]
If you clone the repository, you need to build the project. If you have 0 programming experience, I suggest to just download the binary from the release page.

**Comment by Lofter1** [comment]
I have now included an install script in this repo. Please follow the instructions for your OS in the readme for easy installation.
