### ISSUE TITLE
I can't install on macos Ventura

### ISSUE THREAD

**Issue by DHFTN** [Lofter1/anyflip-downloader#17]
When I try to install on macOS Ventura (M1Pro Macbook Pro), I get the following issues : 
```
Detect Platform and Architecture
Detected darwin arm64
bash: line 28: jq: command not found
Found latest release at 
No release found for platform: darwin
```
How can I pass this problem ?

**Comment by Lofter1** [comment]
I included `jq` in the assumption it was on every system. I rewrote the script to not use `jq` anymore. Should work now. Please try again.

**Comment by Lofter1** [comment]
Oof, okay. That means your user probably doesn't have a `$HOME/.local/share` and no `$HOME/.local/bin` directory.
if there is no `$HOME/.local/share` and no `$HOME/.local/bin` directory, you can create them and it should work. You might also want to add `$HOME/.local/bin` to your path if it didn't exist yet. I will fix the script to do that automatically, but until then, this is the workaround.

**Comment by Lofter1** [comment]
Okay, I updated the install script. Hopefully, everything is installing correctly now. Sorry for all the problems.

**Comment by DHFTN** [comment]
Great! Everything is ok, now! Thank you for your work and corrections !
