### ISSUE TITLE
[Feature] Release for x86_64

### ISSUE THREAD

**Issue by mfuellbier** [Lofter1/anyflip-downloader#27]
**Is your feature request related to a problem? Please describe.**
The install.sh script detects the architecture x86_64 on my Linux system. However, there is no release for that architecture.

**Describe the solution you'd like**
I would like to have a x86_64 architecture release

**Describe alternatives you've considered**
A description how to compile the tool locally would help as well.

I also tried the amd64 release, but this results in the following error:
```
$ anyflip-downloader
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        /home/runner/work/anyflip-downloader/anyflip-downloader/main.go:41 +0x397
$ uname -a
Linux arch 6.5.9-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000 x86_64 GNU/Linux
```

**Comment by Lofter1** [comment]
There actually is a release for x86_64. However, it is called amd64. I fixed the script. It should work now.
