### ISSUE TITLE
Cannot install on linux

### ISSUE THREAD

**Issue by egmondos** [Lofter1/anyflip-downloader#29]
Hi,
unfortunately the install script doesn't work for me. I get a message on line 25 of the install script (bash: line 25: [[x86_64: command not found). I'm not a programmer, but if I read the code correctly, the next line should read "Detected linux amd64", which in my case then reads "Detected linux x86_64" and then consequently does not find a release for linux. 
Tried on linux mint 21.2 and an old MX install.
Any idea why that is and what I'm doing wrong?
Cheers!

**Comment by Lofter1** [comment]
Looking at it, I might have made a mistake assigning the architecture. I will fix it today. Please try again some time tomorrow.
