### ISSUE TITLE
Intalled but command not recognised

### ISSUE THREAD

**Issue by Kara-bit** [Lofter1/anyflip-downloader#30]
**Describe the bug**
I have installed it using script (not go) but powershell says the command isn't recognised. 

OS: [e.g. Windows]
Windows
**To Reproduce**
 Trying to install using the command, for example  " anyflip-downloader https://anyflip.com/zupby/pxnl/ "
 
**Expected behavior**
For the download to happen

**Additional context**
I have tried restarting powershell and computer but that didn't fix it, i can see the folder in local/anyflip-downloader with the exe, licence and readme. In get-commands, the " anyflip-downloader " command is not listed. I have retried installing multiple times.

**Comment by Lofter1** [comment]
It seems like the AppData folder is not necessarily in the path variable. The install script has been fixed.
