### ISSUE TITLE
PDF Files are Empty

### ISSUE THREAD

**Issue by Nazoned** [Lofter1/anyflip-downloader#31]
**Describe the bug**
The download completes, but when the images are converted to a PDF, I end up with an empty file with no extensions.

OS: Windows

**To Reproduce**
Download https://anyflip.com/hveyv/uwkj/basic using the script, and the download completes successfully. After downloading, I get a line stating that it's "Converting to pdf" and it stops there.

**Expected behavior**
An accessible PDF file is to be created after the download.

**Comment by Lofter1** [comment]
The `:` character in the name screwed with windows it seems. The pdf was not recognised as a pdf, but was created successfully. The newest release should have fixed that.

**Comment by Nazoned** [comment]
Ty.
