### ISSUE TITLE
Clicking the .exe opens the window for a second

### ISSUE THREAD

**Issue by direbunny20** [Lofter1/anyflip-downloader#34]
Useage instructions seem a little vague but im not sure what im doing wrong in this instance.

**Comment by Lofter1** [comment]
Please have a look at Issue #8.

This is a CLI program, as can be seen in the GIF in the README. Please have a look at it, especially the install section to make life easier for you. The GIF at a top showstopper usage example and there is also a usage section.  If you don't know how to open a CLI on windows, [this link might help you out](https://www.makeuseof.com/tag/a-beginners-guide-to-the-windows-command-line/)
