### ISSUE TITLE
Installing through recommended script fails on Linux (Mint 21.2) x86_64 system

### ISSUE THREAD

**Issue by turbo-time** [Lofter1/anyflip-downloader#35]
**Describe the bug**
Running the recommended installation script (curl | bash script) fails for my architecture of x86_64.

OS: Linux Mint 21.2 x86_64

The full message returned to the terminal is:
```
Detect Platform and Architecture
bash: line 25: [[x86_64: command not found
Detected linux x86_64

Found latest release at 
No release found for platform: linux
```

**To Reproduce**
To reproduce this behavior, attempt to run the installation script on a system that will return "x86_64" as the architecture variable in the installation script. 

**Expected behavior**
The installation script should work normally for systems that return x86_64 as the architecture.

**Additional context**
Hard coding the installation script to use "amd64" as the architecture made it work correctly. One possible fix would be to check for "x86_64" and change it to "amd64" within the script.

One additional note: my system doesn't register the "anyflip-downloader" command after the installation moves it into /root/.local/bin . Moving it into /usr/bin worked for me.

**Comment by Lofter1** [comment]
The script should work now, though I can't test it right now.

Concerning your last point, you should never execute such scripts as root, and someone doing so is unexpected behavior. When installing with your normal user, the install directory should be fine.

**Comment by adriano2001** [comment]
i have the problem on linux. The same message on the terminal

**Comment by gpare** [comment]
The error `./install.sh: line 25: [[x86_64: command not found` is related to the missing spaces after "[[" and before "]]"; I opened a pull request to fix it.
But you can easily fix it by editing line 25 as: `if [[ "$architecture" == "x86_64" ]]; then`.

**Comment by D-argon** [comment]
Having the same issue 
![image](https://github.com/Lofter1/anyflip-downloader/assets/130792776/cb1950f6-4def-4809-87ed-143211b011fb)
