### ISSUE TITLE
Creates blank PDF

### ISSUE THREAD

**Issue by DorMor973** [Lofter1/anyflip-downloader#51]
**Describe the bug**
App appears to execute as normal but resulting PDF is blank/empty

OS: Windows 11

**To Reproduce**
Download an AnyFlip file which consists of .webp files

**Expected behavior**
downloaded anyflip converted to PDF

**Additional context**
Appears to be a problem when the AnyFlip file contains .webp files instead of .jpeg files. Files are downloaded to the Temp folder as normal but when combined to a PDF the resulting PDF is empty.

**Comment by ThaiEntreprenure** [comment]
yes me too Macm1  i use to copy and place to website convert webp to pdf before its done.

**Comment by Lofter1** [comment]
Hi, I'm having some free time between jobs and could try to resolve this now. If you have any example books that use webp instead of jpeg I could see what I can do

**Comment by DorMor973** [comment]
As an example, you could try:
https://anyflip.com/cmjgl/fxbs/
or for a larger file:
https://anyflip.com/cmjgl/vdhq/

**Comment by Lofter1** [comment]
Should be solved in v1.10. If there are still issues, please reopen the issue with more information.
Converting might take a bit longer now because the fix required using a different library which seems to take a bit longer for converting images to PDF.

**Comment by DorMor973** [comment]
Works fine. Thank you very much. :)
