### ISSUE TITLE
Receiving 403 forbidden for some books

### ISSUE THREAD

**Issue by Lofter1** [Lofter1/anyflip-downloader#7]
I am also getting this error.

```
./anyflip-downloader 'https://anyflip.com/ysunc/yjov/'
Preparing to download
2023/08/09 13:55:44 Received non-200 response: 403 Forbidden
```

_Originally posted by @CoocooFroggy in https://github.com/Lofter1/anyflip-downloader/issues/6#issuecomment-1671376235_

**Comment by nicolasbraun** [comment]
Some files, and sadly those are the one that for some reason do not have the Download PDF button to dowload do not respect the `$url/files/mobile/x.jpg` formalism but have complete random page ID's.

![image](https://github.com/Lofter1/anyflip-downloader/assets/1089363/48ebee86-3af5-4c86-bc33-175d8a021f89)

As it's stand I see no easy fix :(
Great tool though, thanks for your work.

**Comment by Lofter1** [comment]
I will see what I can do there. Any flip needs to get the information where the page is located from somewhere, so it should be possible to find out the page numbers. Might take a bit more Reverse engineering, but I don't think this is impossible.

**Comment by zopad** [comment]
Exact same issue with https://anyflip.com/ydqsm/ybmo/ for example.

**Comment by CoocooFroggy** [comment]
Are the pages not ordered in the configjs `fliphtml5_pages`?

```json
"fliphtml5_pages": [
        {
            "n": [
                "f8584250e08eff083836c07852e3cf48.jpg"
            ],
            "t": "..\/files\/thumb\/d306be09c34c97753666e6e07c866fa2.jpg"
        },
        {
            "n": [
                "fbe28e977e3608ae74e58cd07b5a8368.jpg"
            ],
            "t": "..\/files\/thumb\/60582a1ac2a4be6c1fb4869428b2c550.jpg"
        },
        {
            "n": [
                "fdab1a696e97555774767aa456b5ec53.jpg"
            ],
            "t": "..\/files\/thumb\/6da4b7f13abdd27336d1ff301180ebff.jpg"
        },
        ...
]
```

And then GET `https://online.anyflip.com/{book}/{book}/files/large/{n}.jpg`

**Comment by Lofter1** [comment]
Yes, thank you @CoocooFroggy. That absolutely works. I just need to find a way to parse that. Will work on a regex and hopefully have a patch up today.

**Comment by Lofter1** [comment]
Should be solved in the newest version now.
