### ISSUE TITLE
Exe won't open

### ISSUE THREAD

**Issue by UmbraZeal** [Lofter1/anyflip-downloader#8]
Trying to open the current version of the anyflip-downloader.exe and it won't open, it flashes briefly on my taskbar but then nothing else.

**Comment by Lofter1** [comment]
I'm guessing you are double clicking the exe? This is a console application. You open PowerShell or CMD, navigate to the executable like `cd path/to/exe` (where path to exe is where you put the executable) and then execute the executable like `anyflip-downloader <url>`

If the anyflip-downlaoder exe should still not run, feel free to re-open the issue.
